import { Inter } from 'next/font/google'
import React from 'react';
import StyledComponentsRegistry from './lib/registry'


// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//   )
// }

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'SiteDesign',
  description: 'Generated by create next app',
}


 
export default function RootLayout({ children }) {
  return (
    <html>
      <body className={inter.className}>
        <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
      </body>
    </html>
  )
}